### ISSUE TITLE
Error: Could not find or load main class

### ISSUE THREAD

**Issue by xfthhxk** [luchiniatwork/cambada#11]
Hi! Thanks very much for putting this together. It's the most familiar and complete of the various deps based tools out there for packaging.  I have been trying to get some of my `lein` based projects to use deps and am discovering some issues along the way. 

After building the jar with the patch in #10 I ran into this error:
```shell
$ java -jar ./target/app-1.0.0-SNAPSHOT-standalone.jar
Error: Could not find or load main class app.main
```
I inspected the jar's contents and the class is indeed there.  After some investigation discovered that if the jar contains cryptography libraries ie buddy and/or Bouncy Castle then there are various files present in `META-INF/` with `.SF`, `.RSA` or `.DSA` suffixes which I believe are from signed jars.  `lein` by default excludes these files when building uberjars.

Helpful Stackoverflow post: https://stackoverflow.com/questions/25842559/valid-jar-signature-for-javafx-projects/30922181

**Comment by luchiniatwork** [comment]
Are you using the `--main` argument as in `$ clojure -R:uberjar -m cambada.uberjar --main app.main`?
