### ISSUE TITLE
resources folder is not included, but should be in uberjar.

### ISSUE THREAD

**Issue by middlesphere** [luchiniatwork/cambada#6]
Hello.

I want use cambada to build executable uberjar file.
This is my config
` 
:uberjar {:extra-deps {luchiniatwork/cambada {:mvn/version "1.0.0"}}
                :main-opts ["-m" "cambada.uberjar" "-m" "my.app.core" "--no-copy-source"]}
`
I expect, that cambada will create uberjar file and resources folder will be included in it like leiningen does "lein uberjar". But in practice, cambada is ignoring resource folder and not include it in uberjar.

If I delete "--no-copy-source" parameter, then resources folder will be included in uberjar, but with source code (which is unwanted) and resource folder will be in wrong place.
 
Mike.

**Comment by Aitem** [comment]
Hi @middlesphere 
add in to root your deps.edn file
 :extra-paths ["resources"]

**Comment by middlesphere** [comment]
Hi!

It works! Thank you!

Mike
